# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyMoneyOrgaGui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyMoneyOrgaGui(object):
    def setupUi(self, PyMoneyOrgaGui):
        PyMoneyOrgaGui.setObjectName("PyMoneyOrgaGui")
        PyMoneyOrgaGui.resize(1100, 645)
        self.centralwidget = QtWidgets.QWidget(PyMoneyOrgaGui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1101, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOrganizeAccounts = QtWidgets.QWidget()
        self.tabOrganizeAccounts.setObjectName("tabOrganizeAccounts")
        self.layoutWidget = QtWidgets.QWidget(self.tabOrganizeAccounts)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1071, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.inputAddExpenses = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputAddExpenses.setObjectName("inputAddExpenses")
        self.gridLayout.addWidget(self.inputAddExpenses, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.buttonAddExpenses = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonAddExpenses.setObjectName("buttonAddExpenses")
        self.gridLayout.addWidget(self.buttonAddExpenses, 4, 0, 1, 1)
        self.inputAddIncome = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputAddIncome.setObjectName("inputAddIncome")
        self.gridLayout.addWidget(self.inputAddIncome, 5, 1, 1, 1)
        self.buttonAddIncome = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonAddIncome.setObjectName("buttonAddIncome")
        self.gridLayout.addWidget(self.buttonAddIncome, 5, 0, 1, 1)
        self.tableViewAccounts = QtWidgets.QTableView(self.layoutWidget)
        self.tableViewAccounts.setShowGrid(True)
        self.tableViewAccounts.setObjectName("tableViewAccounts")
        self.gridLayout.addWidget(self.tableViewAccounts, 0, 2, 7, 1)
        self.comboChooseAccount = QtWidgets.QComboBox(self.layoutWidget)
        self.comboChooseAccount.setObjectName("comboChooseAccount")
        self.comboChooseAccount.addItem("")
        self.gridLayout.addWidget(self.comboChooseAccount, 2, 1, 1, 1)
        self.labelChooseAccount = QtWidgets.QLabel(self.layoutWidget)
        self.labelChooseAccount.setObjectName("labelChooseAccount")
        self.gridLayout.addWidget(self.labelChooseAccount, 1, 1, 1, 1)
        self.labelAddExpenses = QtWidgets.QLabel(self.layoutWidget)
        self.labelAddExpenses.setObjectName("labelAddExpenses")
        self.gridLayout.addWidget(self.labelAddExpenses, 3, 1, 1, 1)
        self.tableWidgetTransactions = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidgetTransactions.setObjectName("tableWidgetTransactions")
        self.tableWidgetTransactions.setColumnCount(0)
        self.tableWidgetTransactions.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetTransactions, 0, 3, 7, 1)
        self.tabWidget.addTab(self.tabOrganizeAccounts, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        PyMoneyOrgaGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PyMoneyOrgaGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PyMoneyOrgaGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PyMoneyOrgaGui)
        self.statusbar.setObjectName("statusbar")
        PyMoneyOrgaGui.setStatusBar(self.statusbar)
        self.actionCreate_New_Account = QtWidgets.QAction(PyMoneyOrgaGui)
        self.actionCreate_New_Account.setObjectName("actionCreate_New_Account")
        self.menuFile.addAction(self.actionCreate_New_Account)
        self.menubar.addAction(self.menuFile.menuAction())
        self.labelChooseAccount.setBuddy(self.comboChooseAccount)
        self.labelAddExpenses.setBuddy(self.inputAddExpenses)

        self.retranslateUi(PyMoneyOrgaGui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyMoneyOrgaGui)

    def retranslateUi(self, PyMoneyOrgaGui):
        _translate = QtCore.QCoreApplication.translate
        PyMoneyOrgaGui.setWindowTitle(_translate("PyMoneyOrgaGui", "PyMoneyOrga"))
        self.buttonAddExpenses.setText(_translate("PyMoneyOrgaGui", "new expenses"))
        self.buttonAddIncome.setText(_translate("PyMoneyOrgaGui", "new income"))
        self.comboChooseAccount.setItemText(0, _translate("PyMoneyOrgaGui", "NoAccountSaved"))
        self.labelChooseAccount.setText(_translate("PyMoneyOrgaGui", "choose account"))
        self.labelAddExpenses.setText(_translate("PyMoneyOrgaGui", "amount"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOrganizeAccounts), _translate("PyMoneyOrgaGui", "Organize Expenses"))
        self.menuFile.setTitle(_translate("PyMoneyOrgaGui", "File"))
        self.actionCreate_New_Account.setText(_translate("PyMoneyOrgaGui", "Create New Account"))
