# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyMoneyOrgaGui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyMoneyOrgaGui(object):
    def setupUi(self, PyMoneyOrgaGui):
        PyMoneyOrgaGui.setObjectName("PyMoneyOrgaGui")
        PyMoneyOrgaGui.resize(1192, 747)
        PyMoneyOrgaGui.setMinimumSize(QtCore.QSize(0, 0))
        PyMoneyOrgaGui.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(PyMoneyOrgaGui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOrganizeAccounts = QtWidgets.QWidget()
        self.tabOrganizeAccounts.setObjectName("tabOrganizeAccounts")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabOrganizeAccounts)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.labelAddExpenses = QtWidgets.QLabel(self.tabOrganizeAccounts)
        self.labelAddExpenses.setObjectName("labelAddExpenses")
        self.gridLayout.addWidget(self.labelAddExpenses, 3, 1, 1, 1)
        self.buttonAddExpenses = QtWidgets.QPushButton(self.tabOrganizeAccounts)
        self.buttonAddExpenses.setObjectName("buttonAddExpenses")
        self.gridLayout.addWidget(self.buttonAddExpenses, 4, 0, 1, 1)
        self.tableWidgetAccounts = QtWidgets.QTableWidget(self.tabOrganizeAccounts)
        self.tableWidgetAccounts.setShowGrid(True)
        self.tableWidgetAccounts.setObjectName("tableWidgetAccounts")
        self.tableWidgetAccounts.setColumnCount(2)
        self.tableWidgetAccounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAccounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAccounts.setHorizontalHeaderItem(1, item)
        self.tableWidgetAccounts.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetAccounts.horizontalHeader().setDefaultSectionSize(149)
        self.tableWidgetAccounts.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetAccounts.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetAccounts, 0, 2, 7, 1)
        spacerItem1 = QtWidgets.QSpacerItem(450, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 7, 3, 1, 1)
        self.buttonAddIncome = QtWidgets.QPushButton(self.tabOrganizeAccounts)
        self.buttonAddIncome.setObjectName("buttonAddIncome")
        self.gridLayout.addWidget(self.buttonAddIncome, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(300, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.inputAddExpenses = QtWidgets.QLineEdit(self.tabOrganizeAccounts)
        self.inputAddExpenses.setObjectName("inputAddExpenses")
        self.gridLayout.addWidget(self.inputAddExpenses, 4, 1, 1, 1)
        self.inputAddIncome = QtWidgets.QLineEdit(self.tabOrganizeAccounts)
        self.inputAddIncome.setObjectName("inputAddIncome")
        self.gridLayout.addWidget(self.inputAddIncome, 5, 1, 1, 1)
        self.labelChooseAccount = QtWidgets.QLabel(self.tabOrganizeAccounts)
        self.labelChooseAccount.setObjectName("labelChooseAccount")
        self.gridLayout.addWidget(self.labelChooseAccount, 1, 1, 1, 1)
        self.comboChooseAccount = QtWidgets.QComboBox(self.tabOrganizeAccounts)
        self.comboChooseAccount.setObjectName("comboChooseAccount")
        self.comboChooseAccount.addItem("")
        self.gridLayout.addWidget(self.comboChooseAccount, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(300, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        self.tableWidgetTransactions = QtWidgets.QTableWidget(self.tabOrganizeAccounts)
        self.tableWidgetTransactions.setObjectName("tableWidgetTransactions")
        self.tableWidgetTransactions.setColumnCount(3)
        self.tableWidgetTransactions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(2, item)
        self.tableWidgetTransactions.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetTransactions.horizontalHeader().setDefaultSectionSize(149)
        self.tableWidgetTransactions.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidgetTransactions.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetTransactions.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetTransactions, 0, 3, 7, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOrganizeAccounts, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        PyMoneyOrgaGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PyMoneyOrgaGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1192, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        PyMoneyOrgaGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PyMoneyOrgaGui)
        self.statusbar.setObjectName("statusbar")
        PyMoneyOrgaGui.setStatusBar(self.statusbar)
        self.actionCreate_New_Account = QtWidgets.QAction(PyMoneyOrgaGui)
        self.actionCreate_New_Account.setObjectName("actionCreate_New_Account")
        self.actionDeleteAccount = QtWidgets.QAction(PyMoneyOrgaGui)
        self.actionDeleteAccount.setObjectName("actionDeleteAccount")
        self.actionDelete_Account = QtWidgets.QAction(PyMoneyOrgaGui)
        self.actionDelete_Account.setObjectName("actionDelete_Account")
        self.actionExit = QtWidgets.QAction(PyMoneyOrgaGui)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionCreate_New_Account)
        self.menuFile.addAction(self.actionDeleteAccount)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.labelAddExpenses.setBuddy(self.inputAddExpenses)
        self.labelChooseAccount.setBuddy(self.comboChooseAccount)

        self.retranslateUi(PyMoneyOrgaGui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PyMoneyOrgaGui)
        PyMoneyOrgaGui.setTabOrder(self.tabWidget, self.comboChooseAccount)
        PyMoneyOrgaGui.setTabOrder(self.comboChooseAccount, self.buttonAddExpenses)
        PyMoneyOrgaGui.setTabOrder(self.buttonAddExpenses, self.inputAddExpenses)
        PyMoneyOrgaGui.setTabOrder(self.inputAddExpenses, self.buttonAddIncome)
        PyMoneyOrgaGui.setTabOrder(self.buttonAddIncome, self.inputAddIncome)
        PyMoneyOrgaGui.setTabOrder(self.inputAddIncome, self.tableWidgetAccounts)
        PyMoneyOrgaGui.setTabOrder(self.tableWidgetAccounts, self.tableWidgetTransactions)

    def retranslateUi(self, PyMoneyOrgaGui):
        _translate = QtCore.QCoreApplication.translate
        PyMoneyOrgaGui.setWindowTitle(_translate("PyMoneyOrgaGui", "PyMoneyOrga"))
        self.labelAddExpenses.setText(_translate("PyMoneyOrgaGui", "Amount"))
        self.buttonAddExpenses.setText(_translate("PyMoneyOrgaGui", "New expenses"))
        self.tableWidgetAccounts.setSortingEnabled(True)
        item = self.tableWidgetAccounts.horizontalHeaderItem(0)
        item.setText(_translate("PyMoneyOrgaGui", "Account"))
        item = self.tableWidgetAccounts.horizontalHeaderItem(1)
        item.setText(_translate("PyMoneyOrgaGui", "Balance"))
        self.buttonAddIncome.setText(_translate("PyMoneyOrgaGui", "New income"))
        self.labelChooseAccount.setText(_translate("PyMoneyOrgaGui", "Choose account"))
        self.comboChooseAccount.setItemText(0, _translate("PyMoneyOrgaGui", "NoAccountSaved"))
        self.tableWidgetTransactions.setSortingEnabled(True)
        item = self.tableWidgetTransactions.horizontalHeaderItem(0)
        item.setText(_translate("PyMoneyOrgaGui", "Time stamp"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(1)
        item.setText(_translate("PyMoneyOrgaGui", "Amount"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(2)
        item.setText(_translate("PyMoneyOrgaGui", "New balance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOrganizeAccounts), _translate("PyMoneyOrgaGui", "Organize Expenses"))
        self.menuFile.setTitle(_translate("PyMoneyOrgaGui", "File"))
        self.actionCreate_New_Account.setText(_translate("PyMoneyOrgaGui", "Create New Account"))
        self.actionDeleteAccount.setText(_translate("PyMoneyOrgaGui", "Delete Account"))
        self.actionDelete_Account.setText(_translate("PyMoneyOrgaGui", "Delete Account"))
        self.actionExit.setText(_translate("PyMoneyOrgaGui", "Exit"))
